export default {
    'settings.title': 'Settings',
    'settings.theme': 'Theme',
    'settings.dark': 'Dark',
    'settings.light': 'Light',
    'settings.language': 'Language',
    'settings.swedish': 'Swedish',
    'settings.english': 'English',
    'settings.exportData': 'Export data',
    'settings.exportDataDescription': 'Download your sessions as a JSON file',
    'settings.exportJsonButton': 'Export JSON',
    'settings.importData': 'Import data',
    'settings.importDataDescription': 'Upload sessions from a JSON file',
    'settings.importFileLabel': 'JSON file',
    'settings.importReplaceButton': 'Import (replace)',
    'settings.importMergeButton': 'Import (merge)',
    'settings.importSelectFileFirst': 'Please choose a JSON file first',
    'settings.importSuccessReplace': 'Data imported with replace mode',
    'settings.importSuccessMerge': 'Data imported with merge mode',
    'settings.importError': 'Could not import data',
    'settings.clearStorage': 'Clear stored data',
    'settings.clearStorageDescription': 'This action cannot be undone',
    'settings.clearStorageButton': 'Clear data',
    'settings.clearStorageConfirm': 'Are you sure you want to clear all saved data?'
} as const;
