export default {
    'settings.title': 'Inställningar',
    'settings.theme': 'Tema',
    'settings.dark': 'Mörkt',
    'settings.light': 'Ljust',
    'settings.language': 'Språk',
    'settings.swedish': 'Svenska',
    'settings.english': 'Engelska',
    'settings.exportData': 'Exportera data',
    'settings.exportDataDescription': 'Ladda ner dina sessioner som en JSON-fil',
    'settings.exportJsonButton': 'Exportera JSON',
    'settings.importData': 'Importera data',
    'settings.importDataDescription': 'Ladda upp sessioner från en JSON-fil',
    'settings.importFileLabel': 'JSON-fil',
    'settings.importReplaceButton': 'Importera (ersätt)',
    'settings.importMergeButton': 'Importera (sammanfoga)',
    'settings.importSelectFileFirst': 'Välj en JSON-fil först',
    'settings.importSuccessReplace': 'Data importerades med ersätt-läge',
    'settings.importSuccessMerge': 'Data importerades med sammanfoga-läge',
    'settings.importError': 'Kunde inte importera data',
    'settings.clearStorage': 'Rensa sparad data',
    'settings.clearStorageDescription': 'Detta kan inte återskapas',
    'settings.clearStorageButton': 'Rensa data',
    'settings.clearStorageConfirm': 'Är du säker på att du vill rensa all sparad data?'
} as const;
